### ISSUE TITLE
"Planning and Analysis" tag

### ISSUE THREAD

**Issue by perezal** [trilliumtransit/gtfs-best-practices#1]
I found no use of this tag in the document, though I did find that "Accessibility" and "Accessibility Analysis" were used as tags once each, despite not having a definition.

**Comment by antrim** [comment]
Good call. I removed all of these tags. The "Planning and Analysis" tag was proposed to indicate a growing use of GTFS. However, we did not have broad representation of analysis tools in this process. Conveyal's Transport Analyst was the only such tool. I think it would make sense to hold this back until a later version of the Best Practices.
